### ISSUE TITLE
segmentation fault when running bamfilt

### ISSUE THREAD

**Issue by eoziolor** [phasegenomics/matlock#2]
Hello,

Thanks for providing an option for working with HiC files. I am trying to use matlock, but I am getting a segmentation fault with no more informative message when I try to run it. I prepare my alignments with the exact parameters you mention here and newest versions of bwa, samblaster and samtools:

https://phasegenomics.github.io/2019/09/19/hic-alignment-and-qc.html

I installed matlock on my cluster and with the exact options on the github page. I try to run matlock with:

matlock bamfilt -i <input.bam> -o <output.bam>

The message I receive is:

eoziolor@c9-69:~/phgenome/data/hic_juice/align$ /home/eoziolor/program/matlock/bin/matlock bamfilt -i /home/eoziolor/phgenome/data/hic_juice/align/ph_hic_aligned.bam -o /home/eoziolor/phgenome/data/hic_juice/align/ph_hic_filtered
INFO: RUNNING: /home/eoziolor/program/matlock/bin/matlock -i /home/eoziolor/phgenome/data/hic_juice/align/ph_hic_aligned.bam -o /home/eoziolor/phgenome/data/hic_juice/align/ph_hic_filtered bamfilt 
INFO: detected bam filetype
Segmentation fault

I hope you can help me with this! I am a little stuck with lack of information of how to troubleshoot.

-Elias

**Comment by shawnpg** [comment]
Hi,

Thanks for sharing the issue. Could you tell us what OS you're running on? Also, the easiest way for us to investigate would be for you to send us a core dump. Here's how you can do that:

1. Allow large core dumps: ulimit -c unlimited
2. Remove the matlock binary
3. Change the makefile in the main directory from `CFLAG=-Wall -O3` to `CFLAG=-Wall -g`
4. Run make
5. Re-run your matlock command as above

That should generate a core dump file, which you can attach and send here and we'll take a look.

Thanks!

**Comment by eoziolor** [comment]
Hi Shawn,

Thanks for the prompt response and detailed instructions. I am running this on a Ubuntu 18.04 OS on our local cluster.

I am attaching the core dump below. I appreciate your time in troubleshooting this.

-Elias

[core.txt](https://github.com/phasegenomics/matlock/files/2696164/core.txt)

**Comment by shawnpg** [comment]
Hi Elias,

I think I found the issue. Can you checkout the fix_ubuntu_segfault branch, build, and let me know if the segfault goes away?

Thanks,

Shawn

**Comment by eoziolor** [comment]
Shawn,

Unfortunately, it doesn't. The text is exactly the same. Would you like me to generate another core dump?

-Elias

**Comment by eoziolor** [comment]
Wait, give me a second. I may have pulled the old branch by mistake!

**Comment by eoziolor** [comment]
Shawn,

It seems to work, program runs and output looks proper bam format! 
Thank you so much for troubleshooting this so quickly!

-Elias

**Comment by shawnpg** [comment]
Fantastic, that's great news! I'll submit a pull request to get this submitted to master
